In [1]:
import numpy as np

In [32]:
np.__version__

'1.15.4'

In [26]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a = np.arange(3)
a

array([0, 1, 2])

In [28]:
a[:,np.newaxis].shape

(3, 1)

In [29]:
M+a[:,np.newaxis]

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [30]:
b =  np.arange(6).reshape((6,1,1))
b

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [31]:
M+b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])