# Different strategies for creating **numpy arrays**

- Arrays are data types with fixed size;
- they can be multidimensional;
- used for numeric computation.


In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

Creating an array with zeros!

In [32]:
simple_data = np.zeros(10)
simple_data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
simple_data[0]=0.00000000001

In [34]:
simple_data.shape

(10,)

In [38]:
print(simple_data[0])

1e-11


# Creating an array using the range(n) and numpy.arange(n)

In [2]:
n = 10
new_data = np.array(range(10))
new_data2 = np.arange(10)
print(new_data)


[0 1 2 3 4 5 6 7 8 9]


In [3]:
new_data[0] = 1.2034234
new_data[0]

1

Note that the above array was created with a NumPy integer type! Let's check it out!

In [41]:
new_data.dtype

dtype('int64')

Let's get some help on creating arrays with different number types!

In [43]:
# ? np.array   #Ops... there is a lengthy explanation Here, so I commented!

In [47]:
np.array([0]*10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
teste = np.array([0]*10,dtype=int)
teste

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Creating arrays with various dimensions

A one-dimensional array with ones!

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

A two-dimensional array with ones

In [54]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Functions `np.zeros()` and `np.ones()` work in a similar way. Below a three dimensional array with zeros

In [56]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

A serie of points for making some graphic

In [63]:
x = np.linspace(start=0.0,stop=np.pi,num=100,dtype=np.float64)
print(x)

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

Note that the above command could be written more easily as (my machine is 64 bits):

In [72]:
from numpy import pi
x = np.linspace(0.0,pi,100)
print(x, '\n' )
print(x.dtype.name)

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

**Now, let's make some calculations!**

NumPy uses vectorized functions, which work with scalars and arrays as arguments. The function is applyied to the array element by element, thus making it easier to code (and develop codes in parallel - although I haven't done that yet).

In [75]:
f = np.cos(x)
print(f)

[ 1.          0.99949654  0.99798668  0.99547192  0.99195481  0.98743889
  0.9819287   0.97542979  0.9679487   0.95949297  0.95007112  0.93969262
  0.92836793  0.91610846  0.90292654  0.88883545  0.87384938  0.85798341
  0.84125353  0.82367658  0.80527026  0.78605309  0.76604444  0.74526445
  0.72373404  0.70147489  0.67850941  0.65486073  0.63055267  0.60560969
  0.58005691  0.55392006  0.52722547  0.5         0.47227107  0.44406661
  0.41541501  0.38634513  0.35688622  0.32706796  0.29692038  0.26647381
  0.23575894  0.20480667  0.17364818  0.14231484  0.1108382   0.07924996
  0.04758192  0.01586596 -0.01586596 -0.04758192 -0.07924996 -0.1108382
 -0.14231484 -0.17364818 -0.20480667 -0.23575894 -0.26647381 -0.29692038
 -0.32706796 -0.35688622 -0.38634513 -0.41541501 -0.44406661 -0.47227107
 -0.5        -0.52722547 -0.55392006 -0.58005691 -0.60560969 -0.63055267
 -0.65486073 -0.67850941 -0.70147489 -0.72373404 -0.74526445 -0.76604444
 -0.78605309 -0.80527026 -0.82367658 -0.84125353 -0.

In [11]:
a = 2*np.ones((2,2))
tensor = np.array(a,ndmin=3,)
tensor

array([[[1., 1.],
        [1., 1.]]])

In [ ]:
np.array()