# I/O no Numpy

Formas de salvar em um arquivo usando a biblioteca Numpy

In [1]:
import numpy as np

In [2]:
data = np.random.random((1000,3))
data

array([[0.1869788 , 0.86077075, 0.22497629],
       [0.03586618, 0.63214708, 0.08380428],
       [0.00297935, 0.06029713, 0.50740661],
       ...,
       [0.58518482, 0.04978674, 0.92052349],
       [0.27108555, 0.53478387, 0.52322959],
       [0.03162427, 0.25980587, 0.98380355]])

## 1. Gravar usando ndarray.tofile()

A partir do [Manual](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.tofile.html#numpy.ndarray.tofile).

*Note que eu não consegui fazer com que a linha fosse quebrada*, ou seja, ele cria um enorme string de dados com os números sequencialmente... deve ser uma bobagem, mas não achei um exemplo na internet!

In [3]:
with open('test_random_tofile.dat', 'w') as file:
    data.tofile(file," ")

In [5]:
data[0,0]=1.0;
data[0,1]=1.0;
data[0,2]=1.0;

In [8]:
data

array([[1.        , 1.        , 1.        ],
       [0.03586618, 0.63214708, 0.08380428],
       [0.00297935, 0.06029713, 0.50740661],
       ...,
       [0.58518482, 0.04978674, 0.92052349],
       [0.27108555, 0.53478387, 0.52322959],
       [0.03162427, 0.25980587, 0.98380355]])

## 2. np.savetxt()

This seems really simple! And is, works out of the box.!

In [11]:
np.savetxt('test_random_txt.dat', data, fmt='%1.6f',delimiter = ',', header="Blabla Inicial", footer='Blablabla Final')

# 3. Reading from file - genfromtxt()

Works out of the box. Don't forget to specfy 

delimiter=',' for CSV

In [1]:
#? np.genfromtxt

In [20]:
new_data = np.genfromtxt('test_random_savetxt.dat',dtype=np.float32,usecols=(0,2),delimiter=',')

In [21]:
new_data

array([[0.      , 2.      ],
       [0.035866, 0.083804],
       [0.002979, 0.507407],
       ...,
       [0.585185, 0.920523],
       [0.271086, 0.52323 ],
       [0.031624, 0.983804]], dtype=float32)