In [1]:
import numpy as np

In [3]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    print(a > b)
    if a > b:
        
        return a - b
    else:
        return a + b


In [4]:
myfunc(2,1)

True


1

In [10]:
vmyfunc = np.vectorize(myfunc)
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
vmyfunc(a,b)

False
False
False
False
False


array([ 6,  8, 10, 12])

In [12]:
aa,bb = np.meshgrid(a,b)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [26]:
newaa = aa.reshape((16,))
newbb = bb.reshape((16,))
np.array(list(zip(newaa,newbb) ))

array([[1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [1, 6],
       [2, 6],
       [3, 6],
       [4, 6],
       [1, 7],
       [2, 7],
       [3, 7],
       [4, 7],
       [1, 8],
       [2, 8],
       [3, 8],
       [4, 8]])